name: Question
description: Ask a question about Claude Auto-Commit
title: "[Question] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about Claude Auto-Commit? We're here to help!

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Installation/Setup
        - Usage/Configuration
        - Troubleshooting
        - Feature Clarification
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context (OS, setup, what you're trying to achieve, etc.)
      placeholder: |
        - Operating System: 
        - Version: 
        - What I'm trying to do: 
        - What I've tried: 

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked the README and documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true